import {useCallback,useEffect,useState} from 'react';
import {usePreviewMode} from './usePreviewMode';

type Order={id:string;username:string;status:string;expires_at:string|null;account_id:string|null;order_type?:string};
type Account={id:string;name:string};
type Refund={order_id:string;status:string;note:string};
const active=(o:Order)=>o.order_type!=='extension'&&['approved','delivered','delivery_failed'].includes(o.status)&&!!o.expires_at&&new Date(o.expires_at).getTime()>Date.now();

export default function BookingControls({token,onChanged}:{token:string;onChanged:()=>void}){
 const preview=usePreviewMode();
 const [orders,setOrders]=useState<Order[]>([]),[available,setAvailable]=useState<Account[]>([]),[refunds,setRefunds]=useState<Refund[]>([]);
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[transfer,setTransfer]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{try{const res=await fetch('/api/test-orders',{headers:{Authorization:`Bearer ${token}`}});if(!res.ok)throw new Error('Could not load bookings');const data=await res.json();setOrders(data.orders||[]);setAvailable(data.available||[]);const rr=await fetch('/api/test-orders/v3/refunds',{headers:{Authorization:`Bearer ${token}`}});if(rr.ok)setRefunds((await rr.json()).refunds||[])}catch(e){setError(e instanceof Error?e.message:'Could not load bookings')}},[token]);
 useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[load]);
 async function act(id:string,action:'extend'|'end'|'cancel'|'transfer'|'extra-time',accountId?:string,minutes?:number){
  if(action==='extra-time'&&!window.confirm(`Give this customer ${minutes} extra minutes for free?`))return;
  if(action==='extend'&&!window.confirm(`Confirm you verified a ₹50 ${preview?'TEST ':''}payment from this same customer for 50 more minutes?`))return;
  if(['end','cancel','transfer'].includes(action)&&!window.confirm(`${action==='transfer'?'Migrate this booking to the selected ID, keep the remaining time and queue a reset of the old ID':'Queue a password reset for this account'}?`))return;
  setBusy(id);setError('');setMessage('');try{const response=await fetch(`/api/test-orders/${encodeURIComponent(id)}/${action}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(action==='extend'?{paymentConfirmed:true}:action==='extra-time'?{minutes}:{accountId})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Action failed');setMessage(action==='transfer'?data.message||'Booking migrated.':`${action==='extra-time'?'Extra time added to':action==='extend'?'Extended':action==='end'?'Ending':action==='cancel'?'Cancelled':'Migrated'} ${id}.`);await load();onChanged()}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy('')}
 }
 async function refund(id:string,status:string){setBusy(id);setError('');try{const response=await fetch(`/api/test-orders/${encodeURIComponent(id)}/refund`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({status,note:'Status tracking only; no refund issued by this action'})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not update refund');await load();setMessage(`Refund status updated for ${id}.`)}catch(e){setError(e instanceof Error?e.message:'Could not update refund')}finally{setBusy('')}}
 const current=orders.filter(active);
 return <section className="admin-panel"><div className="flex items-center justify-between gap-3 mb-3"><div><p className="admin-kicker">{preview?'Test bookings':'Bookings'}</p><h2 className="text-xl font-bold">Booking controls</h2></div><button onClick={load} className="admin-secondary">Refresh</button></div>
  <p className="text-sm text-slate-600 mb-4">Extensions stay with the same customer and account. Ending, cancelling or migrating queues a password reset; an old account is unavailable until reset succeeds.</p>
  {error&&<p role="alert" className="text-red-700 text-sm mb-3">{error}</p>}{message&&<p role="status" className="text-emerald-800 text-sm mb-3">{message}</p>}
  {!current.length?<p className="text-slate-500 text-sm">No active bookings.</p>:<div className="space-y-3">{current.map(order=><article key={order.id} className="v3-control-card"><div className="flex justify-between gap-2"><div><strong>{order.username}</strong><p className="text-xs text-slate-500">{order.id} · ends {new Date(order.expires_at!).toLocaleString('en-IN')}</p></div><span className="v3-active-pill">Active</span></div><div className="v3-control-actions"><button disabled={busy===order.id} onClick={()=>act(order.id,'extend')}>+50 min · ₹50</button><button disabled={busy===order.id} onClick={()=>act(order.id,'end')}>End early</button><button disabled={busy===order.id} onClick={()=>act(order.id,'cancel')}>Cancel</button></div><div className="v3-control-actions" aria-label="Complimentary extra time">{[10,15,30].map(minutes=><button key={minutes} disabled={busy===order.id} onClick={()=>act(order.id,'extra-time',undefined,minutes)}>+{minutes} min free</button>)}</div><div className="v3-transfer"><select aria-label={`Transfer ${order.id} to account`} value={transfer[order.id]||''} onChange={e=>setTransfer({...transfer,[order.id]:e.target.value})}><option value="">Migrate to {preview?'sample ':''}account…</option>{available.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><button disabled={!transfer[order.id]||busy===order.id} onClick={()=>act(order.id,'transfer',transfer[order.id])}>Migrate ID</button></div></article>)}</div>}
  {orders.some(o=>o.status==='cancelled')&&<div className="mt-5"><h3 className="font-semibold mb-2">Refund tracking</h3><p className="text-xs text-slate-500 mb-2">Status only. No refund or payment is issued by this control.</p>{orders.filter(o=>o.status==='cancelled').map(o=><div key={o.id} className="flex gap-2 items-center justify-between py-2 border-t border-slate-200"><span className="text-sm truncate">{o.username} · {o.id}</span><select aria-label={`Refund status for ${o.id}`} className="text-xs p-2" disabled={busy===o.id} value={refunds.find(r=>r.order_id===o.id)?.status||'not_requested'} onChange={e=>refund(o.id,e.target.value)}>{['not_requested','requested','processing','completed','rejected'].map(s=><option key={s} value={s}>{s.replace('_',' ')}</option>)}</select></div>)}</div>}
 </section>;
}
