import {useCallback,useEffect,useState} from 'react';
const duration=(h:number)=>h===168?'1 week':h===720?'1 month (30 days)':`${h}h`;
type Order={id:string;username:string;chat_id:string;hours:number;amount:number;status:string;account_id:string|null;created_at:string;claimed_at:string|null;approved_at:string|null;expires_at:string|null;delivered_at:string|null;error:string|null};
type Overview={orders:Order[];summary:{sales:number;revenue:number;bookings:number;customers:number;pending:{n:number};available:number};available:{id:string;name:string}[]};
export default function OrdersPanel({token}:{token:string}){
 const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[hours,setHours]=useState(1),[accountByOrder,setAccountByOrder]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{try{const r=await fetch('/api/test-orders',{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load orders');setData(d);}catch(e){setError(e instanceof Error?e.message:'Could not load orders');}},[token]);
 useEffect(()=>{load();const i=setInterval(load,12000);return()=>clearInterval(i)},[load]);
 async function act(path:string,body:object={}){setBusy(true);setError('');try{const r=await fetch('/api/test-orders/'+path,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Action failed');await load();}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy(false)}}
 return <section className="rounded-2xl border border-slate-200 bg-white p-5 mb-8 shadow-sm">
 <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-bold tracking-wider text-amber-700">SANDBOX · SAMPLE ACCOUNTS · NO REAL PAYMENTS</div><h2 className="font-heading text-xl font-bold text-slate-900 mt-1">Sales & bookings</h2></div><button onClick={()=>load()} className="text-sm border rounded-lg px-3 py-2">Refresh</button></div>
 <p className="text-sm text-slate-600 my-3">The bot reports a customer's payment claim. You verify it yourself before approval. All amounts here are test figures.</p>
 <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mb-5">{[['Total bookings',data?.summary.bookings??0],['Customers',data?.summary.customers??0],['Test sales',data?.summary.sales??0],['Test revenue',`₹${data?.summary.revenue??0}`],['Claims to check',data?.summary.pending.n??0],['Available IDs',data?.summary.available??0]].map(([k,v])=><div className="bg-slate-50 rounded-lg p-3" key={k}><div className="text-xs text-slate-500">{k}</div><div className="font-bold text-xl">{v}</div></div>)}</div>
 <div className="flex flex-wrap gap-2 items-center border-y py-3 mb-3"><label className="text-sm">Try a {''}<select value={hours} onChange={e=>setHours(Number(e.target.value))} className="border rounded px-2 py-1">{[1,2,3,168,720].map(h=><option key={h} value={h}>{duration(h)}</option>)}</select> order</label><button disabled={busy} className="px-3 py-2 rounded-lg text-white bg-slate-900 disabled:opacity-50" onClick={()=>act('demo',{hours})}>Create sample order</button><span className="text-xs text-slate-500">Simulates a customer without connecting Telegram.</span></div>
 {error&&<div role="alert" className="text-red-700 bg-red-50 p-2 rounded mb-3">{error}</div>}
 {!data?.orders.length&&<p className="text-sm text-slate-500">No test orders yet. Start a sample order above or message your test bot.</p>}
 {data?.orders.map(o=><div className="border-b py-4" key={o.id}><div className="flex justify-between gap-3"><div><b>{o.id}</b> <span className="text-slate-500">· {o.username}</span><div className="text-sm">{duration(o.hours)} · ₹{o.amount} · {new Date(o.created_at).toLocaleString()}</div></div><span className="text-sm font-semibold">{o.status.replace(/_/g,' ')}</span></div>
 {o.account_id&&<p className="text-xs text-slate-600">Account: {o.account_id} · Ends: {o.expires_at?new Date(o.expires_at).toLocaleString():'—'}</p>}{o.error&&<p className="text-xs text-red-700">{o.error}</p>}
 {o.status==='awaiting_payment_claim'&&<button disabled={busy} onClick={()=>act(`${o.id}/claim`,{chatId:o.chat_id})} className="text-sm text-blue-700 underline">Simulate customer's payment claim</button>}
 {o.status==='payment_claimed'&&<div className="flex flex-wrap items-center gap-2 mt-3"><label className="text-sm">Assign <select className="border p-2 rounded" value={accountByOrder[o.id]||''} onChange={e=>setAccountByOrder(prev=>({...prev,[o.id]:e.target.value}))}><option value="">Select sample ID</option>{data.available.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button disabled={busy||!accountByOrder[o.id]} onClick={()=>act(`${o.id}/approve`,{accountId:accountByOrder[o.id]})} className="bg-slate-900 text-white text-sm px-3 py-2 rounded disabled:opacity-50">Approve & deliver</button><button disabled={busy} onClick={()=>act(`${o.id}/reject`)} className="border text-sm px-3 py-2 rounded">Reject</button></div>}
 </div>)}
 </section>
}
