import {useCallback,useEffect,useState} from 'react';
type Settings={brand:string;payeeName:string;upiId:string;qrDataUrl:string;support:string;gatewayEnabled:boolean};
export default function PaymentSettingsPanel({token}:{token:string}){
 const [form,setForm]=useState<Settings>({brand:'FlingRoulette',payeeName:'',upiId:'',qrDataUrl:'',support:'',gatewayEnabled:false}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{const r=await fetch('/api/payment-settings',{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load payment settings');setForm({brand:d.brand,payeeName:d.payeeName,upiId:d.upiId,qrDataUrl:d.qrDataUrl,support:d.support,gatewayEnabled:Boolean(d.gatewayEnabled)})},[token]);
 useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 async function file(file:File){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>3*1024*1024){setError('Choose a PNG, JPEG or WebP QR image under 3 MB.');return;}const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Could not read QR image'));reader.readAsDataURL(file)});setForm(value=>({...value,qrDataUrl:data}));setError('')}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/payment-settings',{method:'PUT',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save');setNotice('Payment checkout updated.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not save')}finally{setBusy(false)}}
 const input='w-full border border-slate-300 rounded-lg px-3 py-2 mt-1';
 return <section className="rounded-2xl border border-slate-200 bg-white p-5 mb-8 shadow-sm">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-heading text-xl font-bold text-slate-900">Website payment settings</h2><p className="text-sm text-slate-500 mt-1">Configure the public QR checkout page.</p></div><a href="/checkout" target="_blank" rel="noreferrer" className="text-sm border border-slate-300 rounded-lg px-3 py-2">Open checkout</a></div>
  <div className={`mt-4 rounded-xl p-3 text-sm ${form.gatewayEnabled?'bg-emerald-50 text-emerald-800':'bg-amber-50 text-amber-800'}`}><strong>IMB Payment: {form.gatewayEnabled?'Connected':'Not configured'}</strong><p className="mt-1">{form.gatewayEnabled?'The API token is loaded securely from the server environment.':'Set IMB_API_TOKEN in the server .env file and restart the server to enable gateway checkout.'}</p><p className="mt-1">Webhook URL to enter in IMB: <code className="break-all">{window.location.origin}/api/checkout/imb/webhook</code></p></div>
  <form className="mt-5 space-y-4" onSubmit={save}>
   <div className="grid sm:grid-cols-2 gap-3"><label className="text-sm text-slate-700">Brand name<input className={input} value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}/></label><label className="text-sm text-slate-700">Payee name shown in UPI<input className={input} placeholder="Sahil Mhatre" value={form.payeeName} onChange={e=>setForm({...form,payeeName:e.target.value})}/></label></div>
   <div className="grid sm:grid-cols-2 gap-3"><label className="text-sm text-slate-700">UPI ID<input className={input} placeholder="name@bank" value={form.upiId} onChange={e=>setForm({...form,upiId:e.target.value})}/></label><label className="text-sm text-slate-700">Support username or URL<input className={input} placeholder="@username" value={form.support} onChange={e=>setForm({...form,support:e.target.value})}/></label></div>
   <div><div className="text-sm text-slate-700 mb-2">Payment QR</div><div className="flex flex-wrap items-center gap-3">{form.qrDataUrl&&<img src={form.qrDataUrl} alt="Current payment QR" className="w-28 h-28 object-contain border rounded-xl p-1"/>}<label className="cursor-pointer border border-slate-300 rounded-lg px-3 py-2 text-sm">{form.qrDataUrl?'Replace QR':'Upload QR'}<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const selected=e.target.files?.[0];if(selected)file(selected);e.target.value=''}}/></label>{form.qrDataUrl&&<button type="button" className="text-sm text-red-700" onClick={()=>setForm({...form,qrDataUrl:''})}>Remove QR</button>}</div></div>
   {error&&<p className="text-sm text-red-700 bg-red-50 rounded-lg p-2">{error}</p>}{notice&&<p className="text-sm text-emerald-700 bg-emerald-50 rounded-lg p-2">{notice}</p>}
   <button disabled={busy} className="rounded-lg bg-slate-900 text-white px-4 py-2.5 text-sm font-semibold disabled:opacity-50">{busy?'Saving…':'Save payment settings'}</button>
  </form>
 </section>
}
