import {useCallback,useEffect,useState} from 'react';
type Health={ok:boolean;database:string;uptimeSeconds:number;freeDiskBytes:number;freeMemoryBytes:number;paymentMode:string};
type Backup={name:string;bytes:number};
type Audit={action:string;subject:string;details:string;created_at:string};
export default function PreviewOps({token}:{token:string}){
 const [health,setHealth]=useState<Health|null>(null),[backups,setBackups]=useState<Backup[]>([]),[audit,setAudit]=useState<Audit[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const headers={Authorization:`Bearer ${token}`};
 const load=useCallback(async()=>{try{const [h,b,a]=await Promise.all(['/api/v3/ops/health','/api/v3/ops/backups','/api/v3/ops/audit'].map(url=>fetch(url,{headers:{Authorization:`Bearer ${token}`}})));if(!h.ok||!b.ok||!a.ok)throw new Error('Preview operations unavailable');setHealth(await h.json());setBackups((await b.json()).files||[]);setAudit((await a.json()).entries||[]);setMessage('')}catch(e){setMessage(e instanceof Error?e.message:'Could not load status')}},[token]);
 useEffect(()=>{load()},[load]);
 async function backup(){if(!window.confirm('Create a snapshot of the V3 TEST database only?'))return;setBusy(true);try{const r=await fetch('/api/v3/ops/backup',{method:'POST',headers});const d=await r.json();if(!r.ok)throw new Error(d.error||'Backup failed');await load();setMessage(`Saved ${d.name} on the preview VPS.`)}catch(e){setMessage(e instanceof Error?e.message:'Backup failed')}finally{setBusy(false)}}
 const deploy='git -c safe.directory=/opt/flingroulette-v3 -C /opt/flingroulette-v3 pull --ff-only origin v3/developer-preview && cd /opt/flingroulette-v3/client && npm run build && cd /opt/flingroulette-v3/server && npm run build && systemctl restart flingroulette-v3-preview.service';
 return <section className="admin-panel"><p className="admin-kicker">V3 preview only</p><h2 className="text-xl font-bold mb-2">Operations</h2><p className="text-xs text-slate-500 mb-4">No production controls or live payment access. Updates and rollback require a VPS administrator and are not executed by this web service.</p>{message&&<p role="status" className="text-sm mb-3">{message}</p>}
  <div className="grid grid-cols-2 gap-2 text-sm mb-4"><div className="v3-glass p-3 rounded-2xl">Database <strong className="block">{health?.database||'—'}</strong></div><div className="v3-glass p-3 rounded-2xl">Health <strong className="block">{health?.ok?'Healthy':'Unavailable'}</strong></div><div className="v3-glass p-3 rounded-2xl">Free disk <strong className="block">{health?`${(health.freeDiskBytes/1e9).toFixed(1)} GB`:'—'}</strong></div><div className="v3-glass p-3 rounded-2xl">Uptime <strong className="block">{health?`${Math.floor(health.uptimeSeconds/60)} min`:'—'}</strong></div></div>
  <div className="flex flex-wrap gap-2 mb-3"><button className="admin-secondary" onClick={load}>Health check</button><button className="admin-primary" disabled={busy} onClick={backup}>Create V3 backup</button></div><p className="text-xs text-slate-500 mb-4">{backups.length} backup{backups.length===1?'':'s'} stored in the V3 data directory. Restore is deliberately offline-only.</p>
  <h3 className="font-semibold mb-2">GitHub preview update</h3><p className="text-xs text-slate-500 mb-2">Copy and run this on the preview VPS after reviewing the V3 branch. It cannot update V2.</p><button className="admin-secondary" onClick={()=>navigator.clipboard.writeText(deploy).then(()=>setMessage('V3-only deployment command copied.')).catch(()=>setMessage('Clipboard unavailable; copy it manually.'))}>Copy V3 deploy command</button><code className="block text-[11px] break-all mt-2 p-3 rounded-2xl bg-white/70">{deploy}</code>
  <h3 className="font-semibold mt-5 mb-2">Latest audit activity</h3>{audit.length?audit.slice(0,15).map((entry,index)=><p className="text-xs py-2 border-t border-slate-200" key={`${entry.created_at}-${index}`}>{entry.action} · {entry.subject} · {new Date(entry.created_at).toLocaleString('en-IN')}</p>):<p className="text-xs text-slate-500">No actions recorded yet.</p>}
 </section>;
}
