import {useCallback,useEffect,useMemo,useState} from 'react';
type Period={period:string;bookings:number;revenue:number};
type Refund={order_id:string;status:string;note:string;updated_at:string};
type Report={daily:Period[];monthly:Period[];total:number;successful:number;failed:number;refunds:Refund[]};
const money=(amount:number)=>`₹${amount.toLocaleString('en-IN')}`;

export default function V3Reports({token}:{token:string}){
 const [report,setReport]=useState<Report|null>(null),[error,setError]=useState('');
 const load=useCallback(async()=>{try{const res=await fetch('/api/test-orders/v3/finance',{headers:{Authorization:`Bearer ${token}`}});if(!res.ok)throw new Error('Could not load reports');setReport(await res.json());setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load reports')}},[token]);
 useEffect(()=>{load()},[load]);
 const weekly=useMemo(()=>{const weeks=new Map<string,Period>();for(const day of report?.daily||[]){const date=new Date(`${day.period}T12:00:00Z`),weekday=(date.getUTCDay()+6)%7;date.setUTCDate(date.getUTCDate()-weekday);const key=date.toISOString().slice(0,10);const row=weeks.get(key)||{period:key,bookings:0,revenue:0};row.bookings+=day.bookings;row.revenue+=day.revenue;weeks.set(key,row)}return [...weeks.values()].sort((a,b)=>b.period.localeCompare(a.period))},[report]);
 function exportCsv(){if(!report)return;const rows=[['Period','Date','Bookings','Gross test revenue (INR)'],...report.daily.map(d=>['day',d.period,String(d.bookings),String(d.revenue)]),...weekly.map(d=>['week starting',d.period,String(d.bookings),String(d.revenue)]),...report.monthly.map(d=>['month',d.period,String(d.bookings),String(d.revenue)])];const blob=new Blob(['\uFEFF'+rows.map(row=>row.map(cell=>'"'+cell.replace(/"/g,'""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='flingroulette-v3-test-finance.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="admin-panel"><div className="flex items-center justify-between gap-3"><div><p className="admin-kicker">Test data only</p><h2 className="text-xl font-bold">Detailed reports</h2></div><button onClick={exportCsv} disabled={!report} className="admin-secondary">Export CSV</button></div><p className="text-xs text-slate-500 mt-2 mb-4">Gross confirmed test bookings from 26 Sep 2026; refund statuses are tracked separately and are not deducted. No real payments or refunds.</p>{error&&<p role="alert" className="text-sm text-red-700 mb-3">{error} <button onClick={load}>Retry</button></p>}
 {report&&<><div className="grid grid-cols-3 gap-2 mb-5">{[['Gross',money(report.total)],['Successful',String(report.successful)],['Failed',String(report.failed)]].map(([label,value])=><div key={label} className="v3-glass rounded-2xl p-3"><small className="text-slate-500">{label}</small><strong className="block text-lg">{value}</strong></div>)}</div><div className="grid sm:grid-cols-3 gap-4">{([['Daily',report.daily],['Weekly',weekly],['Monthly',report.monthly]] as const).map(([label,periods])=><div key={label}><h3 className="font-semibold mb-2">{label}</h3><div className="space-y-1 text-sm">{periods.length?periods.slice(0,12).map(row=><div key={row.period} className="flex justify-between gap-2 border-b border-slate-200 py-1.5"><span>{row.period} · {row.bookings}</span><strong>{money(row.revenue)}</strong></div>):<p className="text-slate-500">No test bookings</p>}</div></div>)}</div><h3 className="font-semibold mt-6 mb-2">Refund status</h3>{report.refunds.length?report.refunds.map(item=><p key={item.order_id} className="py-2 text-sm border-t border-slate-200">{item.order_id} · {item.status.replace('_',' ')} <span className="text-slate-500">({new Date(item.updated_at).toLocaleDateString('en-IN')})</span></p>):<p className="text-sm text-slate-500">No refunds tracked.</p>}</>}
 </section>;
}
